# Generated by Django 5.2.4 on 2025-08-07 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('capacity', models.SmallIntegerField(default=30)),
                ('floor', models.SmallIntegerField(default=1)),
                ('dorm_image', models.ImageField(default='hostels.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('contact', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, default='user.jpeg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.SmallIntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('floor', models.SmallIntegerField(default=1)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorm_room', to='student.dormitory')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(default='Male', max_length=6)),
                ('contact', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(blank=True, default='user.jpeg', upload_to='')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_level', to='student.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Dorm_Name', to='student.dormitory')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='student.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_residences', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.SmallIntegerField(default=3)),
                ('methodologies', models.CharField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='student.level')),
            ],
        ),
    ]
