# Generated by Django 5.2.4 on 2025-08-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
    ]
