# Generated by Django 5.2.4 on 2025-08-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_admin_contact_remove_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.level'),
        ),
    ]
