# Generated by Django 5.2.4 on 2025-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
